// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlArSkMf9nPYpnYunPP9v6YKzST0JwqbA',
    appId: '1:40282239780:web:5e2e9cd05736c4bd2b39b1',
    messagingSenderId: '40282239780',
    projectId: 'flyday-broker',
    authDomain: 'flyday-broker.firebaseapp.com',
    storageBucket: 'flyday-broker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYgd93i8KUeLuNCAj3rwpbLUocC2qTzZw',
    appId: '1:40282239780:android:9889d4ff52d556582b39b1',
    messagingSenderId: '40282239780',
    projectId: 'flyday-broker',
    storageBucket: 'flyday-broker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7Vn4tqF31DaxvLvwmdtRdso_WsxjW3Uk',
    appId: '1:40282239780:ios:b5480d9b521df1f02b39b1',
    messagingSenderId: '40282239780',
    projectId: 'flyday-broker',
    storageBucket: 'flyday-broker.appspot.com',
    iosClientId: '40282239780-6dkku83jp75b4d3ni8sufdtfbr0d363b.apps.googleusercontent.com',
    iosBundleId: 'com.ptolemay.flyday.broker.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7Vn4tqF31DaxvLvwmdtRdso_WsxjW3Uk',
    appId: '1:40282239780:ios:5fb44f1a581bc2f22b39b1',
    messagingSenderId: '40282239780',
    projectId: 'flyday-broker',
    storageBucket: 'flyday-broker.appspot.com',
    iosClientId: '40282239780-3vvh6k0e942urln5kpu3gihcnll7g96c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flydayBrocker',
  );
}
